
redis:
  case:
    host: 127.0.0.1
    port: 6379
    timeout: 200
    pool:
      max-idle: 10
      min-idle: 2
      max-wait: 100
      max-active: 100

forest:
  log-response-content: true
  max-connections: 100
  timeout: 3000
  connect-timeout: 3000
  read-timeout: 3000
  variables:
    phpUrl: http://8.142.141.144
    drawUrl: https://wenxin.baidu.com/moduleApi/portal/api

ai-draw:
  api-key:
  secret-key:


oss:
  bookDomain: https://eee.com