
redis:
  case:
    host: 127.0.0.1
    port: 6379
    timeout: 200
    pool:
      max-idle: 10
      min-idle: 2
      max-wait: 100
      max-active: 100

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: ${MYSQL-USER:root}
      password: ${MYSQL-PWD:root}
      url: jdbc:mysql://${MYSQL-HOST:bukeneng-mysql}:${MYSQL-PORT:3306}/${MYSQL-DB:bukenengx_opm}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true

forest:
  log-response-content: true
  max-connections: 100
  timeout: 3000
  connect-timeout: 3000
  read-timeout: 3000
  variables:
    phpUrl: http://8.142.141.144
    drawUrl: https://wenxin.baidu.com/moduleApi/portal/api

ai-draw:
  api-key:
  secret-key:


oss:
  bookDomain: https://eee.com

# 配置文件加密根密码
jasypt:
  encryptor:
    password: pigx
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator